### PR TITLE
Adapt to FHD and do not sort channellist

### PR DESCRIPTION
**Pull request by MegaV0lt**

### CODE REVIEW

**Review by pbiering — CHANGES_REQUESTED** [review]
There is a typo, please fix

"sortd ba names" -?-> "sorted by names"

**Review by pbiering — APPROVED** [review]
Reviewed, looks good

**Comment by pbiering** [comment]
ISO-8859-1 / UTF-8 unalignment found with upstream, see also here: https://github.com/vdr-projects/vdradmin-am/issues/7

**Comment by MegaV0lt** [comment]
Moved to https://github.com/vdr-projects/vdradmin-am/pull/8

**Pull request closed without merging**
